version: "3.8"
services:
  backend:
    #environment:
      #- NODE_ENV=production
    container_name: csm-web
    build: .
    ports:
      - "443:3000"
    networks:
      - csm-net
    depends_on:
      - postgres-db
  
  postgres-db:
    container_name: csm-pgdb
    volumes:
      - data_csm-persist:/var/lib/postgresql/data:wx
    build: ./db/
    networks:
      - csm-net

volumes:
  data_csm-persist: #required for use in above services, or it will be considered mount

networks:
  csm-net:

#simple-mailer

#auth