FROM postgres:14-alpine

ENV POSTGRES_PASSWORD admin
ENV POSTGRES_DB comment-stack-message

#ENV PGDATA /var/lig/postgresql/data #Default

#VOLUME [ "/data_csm-persist" ] #Default location var/lib/docker/volumes

EXPOSE 5432

COPY ./.dump/202112_dump.sql /docker-entrypoint-initdb.d/dump.sql

# RUN addgroup -S basicgroup && adduser -S basicuser -G basicgroup

# USER basicuser

#docker run -d -v data_csm-persist:/var/lib/postgresql/data csm-pgdb